

FROM python:3.9-buster

RUN python3 -m pip install --upgrade pip setuptools wheel
RUN python3 -m pip install --upgrade pip

RUN pip install poetry
COPY poetry.lock pyproject.toml ./

RUN poetry config virtualenvs.create true \
  && poetry install --no-interaction --no-ansi

WORKDIR /users
COPY ./ ./

CMD python3 -m pytest ./tests &&  python3 -m behave
